const messageUtil = {
  OK: "OK",
  EMPTY_FIELD: "Please Enter",
  ALL_READY_EXIST: "Record Already Exist",
  USER_CREATED: "User Created Successfully",
  CLUB_CREATED: "Club Created Successfully",
  RECORD_NOT_CREATED: "Record Not Created",
  NOT_FOUND: "Record Not Found",
  EMAIL_SENT: "Email Sent Successfully",
  CLUB_OWNER_NOT_FOUND: "Club Owner Not Found",
  CLUB_NOT_FOUND: "Club Not Found",
  INCORRECT_PASSWORD: "Incorrect Password",
  LOGIN_SUCCESS: "Login Successfully",
  UNAUTHORIZED: "User not authorized",
  FILENOTUPLOADED: "File Not Uploaded",
  FIRSTNAME_STRING_BASE: "First name should be a type of 'text'",
  FIRSTNAME_STRING_EMPTY: "First Name cannot be an empty field",
  FIRSTNAME_REQUIRED: "First Name is required",
  LASTNAME_STRING_BASE: "Last name should be a type of 'text'",
  LASTNAME_STRING_EMPTY: "Last Name cannot be an empty field",
  LASTNAME_REQUIRED: "Last Name is required",
  POSTALCODE_STRING_BASE: "Postal code should be a type of 'text'",
  POSTALCODE_STRING_EMPTY: "Phone Number cannot be an empty field",
  POSTALCODE_REQUIRED: " Phone Number is required",
  CITY_STRING_BASE: "City should be a type of 'text'",
  CITY_STRING_EMPTY: "City cannot be an empty field",
  CITY_REQUIRED: "City is required",
  EMAIL_STRING_BASE: "Email should be a type of 'text'",
  EMAIL_STRING_EMPTY: "Email cannot be an empty field",
  EMAIL_REQUIRED: "Email is required",
  EMAIL_NOT_VALID: "Email is not valid",
  PASSWORD_STRING_BASE: "Password should be a type of 'text'",
  PASSWORD_STRING_EMPTY: "Password cannot be an empty field",
  PASSWORD_REQUIRED: "Password is required",
  FORGOT_PASSWORD_EMAIL_SENT: "Please check your email",
  PASSWORD_RESET_SUCCESS: "Password reset successfully",
  BASIC_INFO_CREATE: "Basic info created successfully!",
  BASIC_INFO_GET: "Basic info retrieved successfully!",
  BASIC_INFO_NOT_FOUND: "Basic info not found!",
  BASIC_INFO_UPDATE: "Basic info updated successfully!",
  BASIC_INFO_DELETE: "Basic info deleted successfully!",
  TOKEN_EMPTY: "Please login to access these resources",
  MIN_FAQS: "Minimum 1 faq is required",
  USER_DETAILS_FETCHED: "User details fetched",

  // Gig Details
  GIG_DETAILS_CREATE: "Gig details created successfully!",
  GIG_DETAILS_GET: "Gig details retrieved successfully!",
  GIG_DETAILS_NOT_FOUND: "Gig details not found!",
  GIG_DETAILS_UPDATE: "Gig details updated successfully!",
  GIG_DETAILS_DELETE: "Gig details deleted successfully!",
  NUMBER_BASE: "Invalid type, expected a number.",
  BASIC_PRICE_REQUIRED: "Basic package price is required.",
  MAX_IMAGES: "You can upload a maximum of 5 images.",
  INVALID_IMAGE_URL: "Please provide a valid URL for the image.",
  INVALID_VIDEO_URL: "Please provide a valid URL for the video.",
  GIG_ID_REQUIRED: "Gig id is required",
  DATE_REQUIRED: "Date is required",
  TIME_REQUIRED: "Time is required",
  DATE_BASE: "Invalid type, expected a date.",

  // Pricing Package
  PRICING_PACKAGE_CREATE: "Pricing package created successfully!",
  PRICING_PACKAGE_GET: "Pricing package retrieved successfully!",
  PRICING_PACKAGE_NOT_FOUND: "Pricing package not found!",
  PRICING_PACKAGE_UPDATE: "Pricing package updated successfully!",
  PRICING_PACKAGE_DELETE: "Pricing package deleted successfully!",

  // Media
  MEDIA_CREATE: "Media created successfully!",
  MEDIA_GET: "Media retrieved successfully!",
  MEDIA_NOT_FOUND: "Media not found!",
  MEDIA_UPDATE: "Media updated successfully!",
  MEDIA_DELETE: "Media deleted successfully!",

  // Gig
  GIG_CREATE: "Gig created successfully!",
  GIG_GET: "Gig retrieved successfully!",
  GIG_NOT_FOUND: "Gig not found!",
  GIG_UPDATE: "Gig updated successfully!",
  GIG_DELETE: "Gig deleted successfully!",
  GIGS_NOTFOUND: "Gigs not found.",
  GIGS_GET_ALL: "Gigs retrieved successfully.",
  GIGS_GET_ALL: "All gigs retrieved successfully",
  GIGS_NOT_FOUND: "No gigs found",
  GIGS_GET_BY_NAME: "Filtered gigs retrieved successfully",
  GIGS_NOT_FOUND: "No gigs found with the specified name",
  GIGS_NOT_FOUND_BY_CATEGORY: "No gigs found with the specified category",
  GIG_NAME_REQUIRED: "Gig name is required to filter",
  GIG_CATEGORY_REQUIRED: "Gig category is required to filter",
  STRING_BASE: "The value should be a valid string.",
  STRING_EMPTY: "This field cannot be empty.",
  STRING_REQUIRED: "This field is required.",
  CATEGORY_REQUIRED: "Please select a category.",
  SUBCATEGORY_REQUIRED: "Please select a subcategory.",
  MAX_TAGS: "You can only enter up to 5 search tags.",
  GIGID_EMPTY: "Gig id is required",
  USERID_EMPLTY: "user id is required",
  PRICE_REQUIRED: "Price is required",
  REVISION_REQUIRED: "revision is required",
  SERVICES_REQUIRED: "Services is required",
  OBJECT_BASE: "The Extrafast must be an object.",


  // reviews
  REVIEW_CREATED: "Review added successfully",
  REVIEWS_FETCHED: "Review retrieve successfully",
  REVIEWS_FETCHED: "Reviews fetched sucessfully",
  REVIEW_UPDATED: "Reviews update successfully",
  REVIEW_DELETED: "Review Deleted successfully",
  RATING_REQUIRED: 'The rating field is required.',
  RATING_MIN: 'The rating must be at least 1.',
  RATING_MAX: 'The rating must not exceed 5.',
  GIGID_REQUIRED: 'The gigId field is required.',
  COMMENT_REQUIRED: 'The comment field is required.',

  // category
  CATEGORY_CREATED: "Category created successfully",
  CATEGORIES_FETCHED: "Categories fetched successfully",
  CATEGORY_UPDATED: "Category update successfully",
  CATEGORY_DELETED: "Category delete successfully",
  CATEGORY_NOT_FOUND: "Category not found",

  // SUB CATEGORY 
  SUBCATEGORY_CREATED: "Subcategory created successfully",
  SUBCATEGORIES_FETCHED: "Subcategories fetched successfully",
  SUBCATEGORY_UPDATED: "Subcategory update successfully",
  SUBCATEGORY_DELETED: "Subcategory delete successfully",
  SUBCATEGORY_FETCHED: "Subcategory fetched successfully",

  // bookings
  BOOKING_CREATED: "Booking created successfully",
  BOOKINGS_FETCHED: "Bookings fetched successfully",
  BOOKING_FETCHED: "Booking fetched successfully",
  BOOKING_UPDATED: "Booking updated successfully",
  BOOKING_DELETED: "Booking deleted successfully",
  BOOKING_NOT_FOUND: "Booking not found",

  // address  validation 
    STREET_REQUIRED: "Street is required",
    CITY_REQUIRED: "City is required",
    STATE_REQUIRED: "State is required",
    ZIPCODE_REQUIRED: "Zip Code is required",
    COUNTRY_REQUIRED: "Country is required",

    // pricing
    PRICING_CREATED: "Pricing created successfully",
    PRICING_FETCHED: "Pricing fetched successfully",
    PRICING_DELETED: "Pricing deleted successfully",

    // revision 
    REVISION_CREATED: "Revision created successfully",
    REVISIONS_FETCHED: "Revisions fetched successfully",
    REVISION_DELETED: "Revision deleted successfully",
    
  
};
export default messageUtil;
